AllCops:
  TargetRubyVersion: 2.5.0

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: native, lf, crlf
Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Rails/BulkChangeTable:
  Enabled: false

# Offense count: 2
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/rails_helper.rb'
    - 'spec/support/carrierwave.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'db/migrate/**/'