# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: native, lf, crlf
Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Max: 25

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
