# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: native, lf, crlf
Layout/EndOfLine:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'
  